practice-app/back-end/app.js, practice-app/back-end/routes/filter_user_tweets.js
A request example:
http://localhost:3000/filter_user_tweets?user=ARealityEvent&mentioned=Apple&count=10
Let me know if anything is missing.
=> Searching tweets a vendor is mentioned by another user

practice-app/back-end/test/test-filter_user_tweets.js
Let me know if anything is missing/mistaken.
=> Testcase for filter_user_tweets.js

app/frontend/package-lock.json, app/frontend/src/App.js, app/frontend/src/App.test.js, app/frontend/src/common/NoMatch.js, app/frontend/src/home/Home.js, app/frontend/src/home/Home.test.js, app/frontend/src/index.js, app/frontend/src/login/Login.js
Changed project structure so editing would be easier. Also added one example test case and removed old one. Test with `npm test`. Note that this test case is just for example and to be changed in future. Also there are different router types in App.js. You may choose suitable one for your task.
=> Changed project structure

app/frontend/src/login/Login.js, app/frontend/src/login/Validate.js, app/frontend/src/signup/Signup.js, app/frontend/src/signup/Validate.js
This is validation for signup and login pages.
Closes #132
=> Login validation

app/backend/.gitignore, app/backend/Dockerfile, app/backend/README.md, app/backend/api/__init__.py, app/backend/api/admin.py, app/backend/api/models/__init__.py, app/backend/api/models/users.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/users.py, app/backend/api/templates/swagger-ui.html, app/backend/api/urls.py, app/backend/api/utils/__init__.py, app/backend/api/utils/utils.py, app/backend/api/views/__init__.py, app/backend/api/views/users.py, app/backend/bupazar/settings.py, app/backend/bupazar/urls.py, app/backend/init.sh, app/backend/requirements.txt
* Token based authentication, registration, login, logout, changing password and updating profile features are added.
Closes #142, closes #143, closes #144, closes #145 and closes #147
=> Adding Multiple Features

app/frontend/package-lock.json, app/frontend/package.json, app/frontend/src/App.js, app/frontend/src/common/Requests.js, app/frontend/src/common/ServerUrl.js, app/frontend/src/login/Login.js, app/frontend/src/signup/Signup.js, app/frontend/src/signup/Validate.js, app/frontend/src/signup/Vendor.js
Connected login to backend. Also made some small UI changes. Vendor page is also created.
Closes #133 and #135
=> Login connect backend

app/frontend/Dockerfile
Added dockerfile in order to deploy frontend on the web server
=> frontend/ add dockerfile

app/mobile/BuPazar/app/build.gradle, app/mobile/BuPazar/app/src/main/AndroidManifest.xml, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/LoginRequest.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/LoginResponse.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/login/LoginActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/ServiceBuilder.kt
Now login credentials will be checked and login properly
=> mobile - Login and Homepage redirection

app/mobile/BuPazar/app/build.gradle, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/Product.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ProductAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/home/HomepageActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/home/ProductsAdapter.java, app/mobile/BuPazar/app/src/main/res/layout/homepage_activity.xml, app/mobile/BuPazar/app/src/main/res/layout/item_product.xml, app/mobile/BuPazar/app/src/main/res/values/strings.xml
home page implementation, products recycleview added
=> Mobile yasar

app/frontend/src/App.js, app/frontend/src/components/SimpleGridList.js, app/frontend/src/components/tileData.js, app/frontend/src/product/product.js
Necessary product changes have been made under profile page branch. (Initialization and static modelling of product page)
=> Product Page

app/backend/.gitignore, app/backend/api/admin.py, app/backend/api/models/__init__.py, app/backend/api/models/products.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/products.py, app/backend/api/urls.py, app/backend/api/utils/__init__.py, app/backend/api/utils/utils.py, app/backend/api/views/__init__.py, app/backend/api/views/products.py, app/backend/bupazar/settings.py, app/backend/bupazar/storage_backends.py, app/backend/requirements.txt
* Product and category models are created.
* Add product component for vendor is added.
endpoints: http://127.0.0.1:8000/api/products/ and http://127.0.0.1:8000/api/products/opts/add/
* Closes #184
=> Backend/ Product Model and Add Product Feature for Vendor

app/backend/api/models/__init__.py, app/backend/api/models/products.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/products.py, app/backend/api/urls.py, app/backend/api/views/__init__.py, app/backend/api/views/products.py, app/backend/bupazar/settings.py
Implemented Product List feature.
Example cUrl commands (Token belongs to the user with id 49)
curl --location --request GET 'http://127.0.0.1:8000/api/product-lists/'
curl --location --request POST 'http://127.0.0.1:8000/api/product-lists/opts/add/' \
--header 'Authorization: Token 7b819cd591cf0e401a4b4d6908fbe927a3c342bc' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "test list 5"
}'
curl --location --request POST 'http://127.0.0.1:8000/api/product-lists/opts/add_product/' \
--header 'Authorization: Token 7b819cd591cf0e401a4b4d6908fbe927a3c342bc' \
--header 'Content-Type: application/json' \
--data-raw '{
"list_id": 2,
"product_id": 19
}'
curl --location --request POST 'http://127.0.0.1:8000/api/product-lists/opts/remove_product/' \
--header 'Authorization: Token …
=> Backend feature product lists

.gitignore, app/frontend/src/components/SimpleGridList.js, app/frontend/src/home/Home.js, app/frontend/src/home/Navbar.js, app/frontend/src/product/CommentList.js, app/frontend/src/product/product.js
Users can now click to info button of a product to go to corresponding product page and view details.
Product page is not completed in terms of liking, listing, purchasing, and comments section since these functionalities have not been implemented yet. 
Closes #176 for now
=> frontend/ redirections from home to product page

app/frontend/src/components/Footer.js, app/frontend/src/profile/Profile.js, app/frontend/src/profile/ValidateEditProfile.js
Completes edit-profile  for customers. Includes:
1. UI design 
2.Backend connection
3.Validation
4.Error messages
Closes #213
=> Edit profile

app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_address.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_help_24.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_keyboard_arrow_right_24.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_message_24.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_order.xml, app/mobile/BuPazar/app/src/main/res/drawable/ic_baseline_person_24.xml, app/mobile/BuPazar/app/src/main/res/drawable/rectangle_border.xml, app/mobile/BuPazar/app/src/main/res/drawable/transparent_rectangle_border.xml, app/mobile/BuPazar/app/src/main/res/layout/fragment_my_account.xml
Layout implementation for the my account tab is now complete
=> my account tab layout implementation

app/backend/api/models/products.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/products.py, app/backend/api/views/products.py
According to the feedback, comment and rating functionality is merged. Getting all comments of a given product is implemented.
=> Backend feature comment

app/backend/api/models/__init__.py, app/backend/api/models/orders.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/orders.py, app/backend/api/urls.py, app/backend/api/views/__init__.py, app/backend/api/views/orders.py
Add/delete functionality is added as well
=> backend/ Credit card information 

app/frontend/src/components/CategoryTab.js
- Subcategories are added with mouse hover effect
=> frontend/ Subcategories are added to category tab

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/AllProductsResponse.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ProductAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ProductDetails.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/home/HomepageActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/login/LoginActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/HomepageFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/ServiceBuilder.kt, app/mobile/BuPazar/app/src/main/res/layout/fragment_homepage.xml, app/mobile/BuPazar/app/src/main/res/layout/item_product.xml
Fixing the previous commit problem
=> fixing commit problem

app/frontend/src/home/Navbar.js, app/frontend/src/product/AddProduct.js
Now you can additionally choose subcategory, brand name and discount rate. This is complete version of add product. Also fixes 2 small bug in navigation bar. Closes #212.
=> Frontend addproduct complete

app/frontend/src/App.js, app/frontend/src/home/Navbar.js, app/frontend/src/list/Favorites.js, app/frontend/src/list/ListPage.js, app/frontend/src/list/ListsPage.js, app/frontend/src/product/product.js, app/frontend/src/profile/Profile.js
=> frontend/ lists

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ForgotPasswordRequest.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/login/LoginActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/login/ForgotPasswordFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/res/layout/fragment_forgot_password.xml
user can reset his/her password when he/she forget it.
=> mobile-forgot my password button activated.

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/CommentAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/CommentDetails.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/CommentRequest.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/ProductFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/res/drawable/shape.xml, app/mobile/BuPazar/app/src/main/res/layout/fragment_product.xml, app/mobile/BuPazar/app/src/main/res/layout/row_comment.xml
users can see comments and rating on the product.
=> mobile-comment and rating display are implemented

app/frontend/src/App.js, app/frontend/src/home/Navbar.js, app/frontend/src/profile/Profile.js, app/frontend/src/vendorproduct/Vendoreditproduct.js, app/frontend/src/vendorproduct/Vendorproduct.js, app/frontend/src/vendorproduct/Vendorproductlist.js
Vendor is able to edit the product information and display vendor product in my product page. Also navbar changes according to vendor or customer.
=> Vendorprofilefixes

app/frontend/Dockerfile, app/frontend/src/App.js, app/frontend/src/payment/Payment.js, app/frontend/src/payment/ValidateAddress.js, app/frontend/src/profile/Profile.js, app/frontend/src/profile/ValidateEditProfile.js
- More structured address fields are added to profile update and payment pages.
- Now address has 5 fields (address line, city, state, zip code, country)
=> Frontend structured address

app/backend/api/models/search_history.py, app/backend/api/tests/__init__.py, app/backend/api/tests/test_recommend_product.py, app/backend/api/urls.py, app/backend/api/views/__init__.py, app/backend/api/views/products_filter.py, app/backend/api/views/recommendation.py
* Recommendation for guest users is implemented.
* Recommendation for authenticated customers is implemented considering their search history, cart, lists and purchases. It also supports finding semantically similar products.
* Recommendation system is tested with an unit test.
Closes #332 .
=> Backend/ Recommendation System

app/backend/api/models/__init__.py, app/backend/api/models/alarm.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/alarm.py, app/backend/api/urls.py, app/backend/api/views/__init__.py, app/backend/api/views/alarm.py, app/backend/api/views/orders_details.py
* Price alarm for customers is implemented in order to be notified if the price of product goes below the chosen price.
* Response bug is fixed for customer cancel order.
Closes #345
=> Backend/ Alarms

app/frontend/src/App.js, app/frontend/src/profile/Profile.js, app/frontend/src/savedCards/SavedCards.js
- Now user is able to see saved credit cards from profile page.
- New credit card can be added or previously saved ones can be deleted.
Closes #327
=> Frontend saved credit cards

app/frontend/src/App.js, app/frontend/src/login/Login.js, app/frontend/src/product/product.js, app/frontend/src/profile/Assessments.js, app/frontend/src/profile/Profile.js, app/frontend/src/vendorproduct/VendorProductTypes.js, app/frontend/src/vendorproduct/Vendorproduct.js, app/frontend/src/vendorproduct/Vendorproductlist.js
- Min rating on products is now 1. 0 is treated as the customer forgot to rate.
- Vendor can view the types of product they sell on their my products pages.
- Vendor rating is added to product pages as read-only.
- Assessments page of customers is implemented.
Closes #335 and #336
=> frontend/ assessments

app/backend/api/models/__init__.py, app/backend/api/models/orders.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/orders.py, app/backend/api/urls.py, app/backend/api/views/__init__.py, app/backend/api/views/orders_details.py
- Shipment model is added.
- add_shipment and get_shipment endpoints are implemented.
=> backend/ Shipment model and add/get shipment endpoints are implemented.

app/backend/api/views/products_details.py, app/backend/api/views/products_filter.py
* Response descriptions of swagger for products related endpoints are fixed.
Closes #369
=> Backend/ Fixing Response Descriptions of Swagger

app/frontend/src/App.js, app/frontend/src/login/Forgot.js, app/frontend/src/login/ForgotChange.js, app/frontend/src/login/Login.js
Completed forgot password feature.
Closes #134
=> Frontend forgot complete

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/HomepageProductAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/HomepageFragment.kt
Users can now search products by typing onto the search bar on the homepage. Searchbar looks for products based on their name, brand, vendor, or category.
=> mobile/homepage search bar is implemented.

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/Chat.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ChatCreateRequest.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ChatRequest.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/GetAllChatResponse.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/GetLastMessageResponse.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/Message.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/MessageAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/login/LoginActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/message/ChatActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/activity/message/MessageMainActivity.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/ProductFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/res/layout/activity_message_main.xml
Some parameters are changed in the backend, so I updated. and add the date information
=> Mobile/ mobile chat is updated according to the new updates on endpoints

app/backend/api/models/notifications.py, app/backend/api/serializers/__init__.py, app/backend/api/serializers/notifications.py, app/backend/api/views/notifications.py, app/backend/api/views/orders.py
* Seen information is added to notification model.
* Endpoint that marks notification as seen is implemented.
* Bug in order status change notification is fixed.
* Bug in return value of product in notification response which raises exception is fixed.
Closes #383
=> Backend/ Bug Fixes and Notification Seen Info

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/interface/RestApi.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/NotificationAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/NotificationResponse.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/ProductDetails.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/MyAccountFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/NotificationFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/service/RestApiService.kt, app/mobile/BuPazar/app/src/main/res/layout/fragment_my_account.xml, app/mobile/BuPazar/app/src/main/res/layout/fragment_notification.xml, app/mobile/BuPazar/app/src/main/res/layout/notification_row.xml, app/mobile/BuPazar/app/src/main/res/values/strings.xml
User can see notifications on the account page.
=> Mobile-notification 

app/frontend/src/App.js, app/frontend/src/components/dialog.js, app/frontend/src/components/gridlistforsearch.js, app/frontend/src/product/product.js, app/frontend/src/search/search.js, app/frontend/src/signup/Signup.js, app/frontend/src/vendorpublic/vendorpublicview.js, app/frontend/src/vendorpublic/vendorpublicviewproduclist.js
After searching vendornames now one can go to vendorpublic page .Necessary connections with other pages our done. Also currency showcasing is implemented in product page. Shopping chart stock bug and snackbar bugs fixed.
=> Vendorpublicview

app/frontend/src/payment/Payment.js
Previously, users can proceed with empty cart, now it's fixed.
Fixes #319
=> frontend/ fix bug user can't proceed w/ empty cart

app/frontend/src/App.js, app/frontend/src/agreements/UserAgreement.js, app/frontend/src/payment/Payment.js
- Users are expected to accept the user agreement policy in payment.
=> frontend/ user-agreement policy added

app/frontend/package-lock.json, app/frontend/src/App.js, app/frontend/src/agreements/Terms.js, app/frontend/src/signup/Signup.js
Terms and Conditions are now on sign up page
Fixes #409
=> Frontend terms conditions

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/VendorOrderDetailFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/VendorOrdersFragment.kt
Order status is now modified correctly after being updated from the vendor order details page. Also, recent orders are now shown at top of the vendor orders page.
=> mobile/instant delivery bug fix & recent orders shown at top vendor orders page

app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/CartProductAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/CreditCardAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/HomepageProductAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/OrderPhotosAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/PreviousOrdersAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/model/VendorOrdersAdapter.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/HomepageFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/OrderFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/PayWithAnotherCardFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/ProductFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/SpesificProductsFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/SuccessfulOrderFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/VendorOrderDetailFragment.kt, app/mobile/BuPazar/app/src/main/java/com/example/bupazar/page/fragment/VendorOrdersFragment.kt
Fragments and adapters created by myself has been commented.
=> mobile/commenting of the fragments&adapters
